import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import AuthProvider from "@/components/providers/AuthProvider";
import AppProvider from "@/components/providers/AppProvider";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// import localFont from "next/font/local";
// const daggerSquare = localFont({
//   src: "./fonts/DAGGERSQUARE.otf",
//   variable: "--font-dagger-square",
//   display: "swap",
// });

export const metadata: Metadata = {
  title: "claude-dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={`font-poppins antialiased`}>
        <AuthProvider>
          <AppProvider>

            {children}
            <Toaster />

          </AppProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
